-- Windows Neovim Configuration
require("plugins")
require("keybindings")
require("globals")
require("config.cmp")
require("config.lsp")
require("config.dap")
require("config.telescope")
require("config.lualine")
require("config.gotopreview")
require("config.csvview")
require("config.pqf")
require("config.treesitter")
