-- Windows Neovim Configuration
require("plugins")
require("keybindings")
require("globals")
require("plugins.nvim-cmp")
require("plugins.lsp")
require("plugins.dap")
require("plugins.telescope")
require("plugins.lualine")
require("plugins.goto-preview")
require("plugins.csvview")
require("plugins.nvim-pqf")
require("plugins.nvim-treesitter")
require("plugins.nvim-lightbulb")
require("plugins.rainbow-delimiters")
