-- Windows Neovim Configuration
require("plugins")
require("keybindings")
require("globals")
require("lsp")
require("plugins.harbour")
require("plugins.gitsigns")
require("plugins.nvim-cmp")
require("plugins.nvim-dap")
require("plugins.telescope")
require("plugins.lualine")
require("plugins.csvview")
require("plugins.nvim-pqf")
require("plugins.nvim-treesitter")
require("plugins.easy-dotnet")
