-- MacOS Neovim Configuration
require("plugins")
require("keybindings")
require("globals")
require("lsp")
require("plugins.nvim-cmp")
require("plugins.nvim-dap")
require("plugins.luasnip")
require("plugins.vimtex")
require("plugins.telescope")
require("plugins.lualine")
require("plugins.goto-preview")
require("plugins.csvview")
require("plugins.nvim-pqf")
require("plugins.nvim-treesitter")
require("plugins.lean")
require("plugins.easy-dotnet")
