-- MacOS Neovim Configuration
require("plugins")
require("keybindings")
require("globals")
require("config.nvimcmp")
require("config.lsp")
require("config.dap")
require("config.luasnip")
require("config.vimtex")
require("config.telescope")
require("config.lualine")
require("config.gotopreview")
require("config.csvview")
require("config.pqf")
require("config.gitconflict")
require("config.treesitter")
