-- PLUGIN MANAGEMENT --
-- Manage plugins with vim-plug.
local Plug = vim.fn["plug#"]
vim.call("plug#begin")

Plug("junegunn/fzf", { ["do"] = ":call fzf#install()" })
Plug("junegunn/fzf.vim")
Plug("wincent/ferret")
Plug("nvim-lualine/lualine.nvim")
Plug("vague-theme/vague.nvim")
Plug("scrooloose/nerdtree")
Plug("tpope/vim-dispatch")
Plug("tpope/vim-unimpaired")
Plug("tpope/vim-vinegar")
Plug("tpope/vim-fugitive")
Plug("tpope/vim-repeat")
Plug("tpope/vim-surround")
Plug("lewis6991/gitsigns.nvim")
Plug("yorickpeterse/nvim-pqf")
Plug("ctrlpvim/ctrlp.vim")
Plug("mileszs/ack.vim")
Plug("easymotion/vim-easymotion")
Plug("tomtom/tcomment_vim")
Plug("hrsh7th/cmp-nvim-lsp")
Plug("hrsh7th/cmp-buffer")
Plug("hrsh7th/cmp-path")
Plug("hrsh7th/cmp-cmdline")
Plug("hrsh7th/nvim-cmp")
Plug("lervag/vimtex")
Plug("L3MON4D3/LuaSnip", { ["do"] = ":call make install_jsregexp" })
Plug("saadparwaiz1/cmp_luasnip")
Plug("nvim-lua/plenary.nvim")
Plug("Julian/lean.nvim")
Plug("nvim-telescope/telescope.nvim")
Plug("nvim-telescope/telescope-ui-select.nvim")
Plug("rmagatti/logger.nvim")
Plug("rmagatti/goto-preview")
Plug("mfussenegger/nvim-dap")
Plug("mfussenegger/nvim-dap-python")
Plug("mfussenegger/nvim-jdtls")
Plug("nvim-neotest/nvim-nio")
Plug("rcarriga/nvim-dap-ui")
Plug("mrcjkb/haskell-tools.nvim")
Plug("hat0uma/csvview.nvim")
Plug("JuliaEditorSupport/julia-vim")
Plug("seblyng/roslyn.nvim")
Plug("Cliffback/netcoredbg-macOS-arm64.nvim")
Plug("nvim-treesitter/nvim-treesitter", { ["do"] = ":TSUpdate" })

vim.call("plug#end")
